### ISSUE TITLE
Refinery stops accepting events from Otel Collector after config update

### ISSUE THREAD

**Issue by bixu** [honeycombio/helm-charts#101]
**Versions**

Charts:
```
- name: opentelemetry-collector
  version: 0.8.1
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
- name: refinery
  version: 1.3.0
  repository: https://honeycombio.github.io/helm-charts
```

Helm: ArgoCD (Helm 3 compatible)
Kubernetes cluster: 1.19 EKS

**Steps to reproduce**

1. Scale out a single Otel Collector to 2 or more replicas (behind and NLB) and point them at a K8s Refinery cluster in the same K8s cluster:

```yaml
opentelemetry-collector:
  fullnameOverride: opentelemetry-collector
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.37.1
  command:
    name: otelcontribcol
    extraArgs: []
  agentCollector:
    enabled: false
  standaloneCollector:
    enabled: true
    replicaCount: 4
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
  service:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: host.domain.name
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <some acm cert>
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "4317,4318,9411,14250,14268"
      service.beta.kubernetes.io/aws-load-balancer-alpn-policy: HTTP2Preferred
  ports:
    otlp:
      enabled: true
      containerPort: 4317
      servicePort: 4317
      hostPort: 4317
      protocol: TCP
    otlphttp:
      enabled: true
      containerPort: 4318
      servicePort: 4318
      hostPort: 4318
      protocol: TCP
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: true
      containerPort: 14268
      servicePort: 14268
      hostPort: 14268
      protocol: TCP
    jaeger-grpc:
      enabled: true
      containerPort: 14250
      servicePort: 14250
      hostPort: 14250
      protocol: TCP
    zipkin:
      enabled: true
      containerPort: 9411
      servicePort: 9411
      hostPort: 9411
      protocol: TCP
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      otlp/refinery:
        endpoint: opentelemetry-collector-refinery:4317
        tls:
          insecure: true
        headers:
          x-honeycomb-team: <api key>
          x-honeycomb-dataset: <env>
      otlp/honeycomb-metrics:
        endpoint: api.honeycomb.io:443
        headers:
          x-honeycomb-team: <api key>
          x-honeycomb-dataset: <env>-metrics
    service:
      pipelines:
        traces:
          receivers:
            - otlp
          processors: 
            - memory_limiter
            - batch
          exporters:
            - otlp/refinery
        metrics:
          receivers:
            - otlp
            - prometheus
          processors: 
            - memory_limiter
            - batch
          exporters:
            - otlp/honeycomb-metrics
        logs:
          receivers:
            - otlp
          processors: 
            - memory_limiter
            - batch
``` 

2. Add a field to the Refinery rule field list

```yaml
# original rules:
  rules:
    GoalSampleRate: 1
    Weight: 0.5
    FieldList:
      - http.method
      - http.status
      - service.name
      - messaging.kafka.partition
      - messaging.destination
      
# new rules:
  rules:
    GoalSampleRate: 1
    Weight: 0.5
    FieldList:
      - http.method
      - http.status
      - service.name
      - messaging.kafka.partition
      - messaging.destination
      - rpc.grpc.status_code
```

3. Observe `context deadline exceeded` messages in the Otel Collector logs like:

```
Exporting failed. Will retry the request after interval
error: failed to push trace data via OTLP exporter: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

4. Workaround is to manually delete Refinery pods one at a time. However, this results in a several minute time-to-recovery. May also need to delete Otel Collector pods if they continue to log errors.
