### ISSUE TITLE
[refinery] several operators fail, some without an error, if not single quoted

### ISSUE THREAD

**Issue by RainofTerra** [honeycombio/helm-charts#286]
The `!=`, `>`, `>=` operators only work if single quoted, but only `>=` throws an error - `!=` and `>` silently pass an empty operator value to refinery, which causes the pods to fail to start.

**Versions**

Chart: 2.2.0
Helm: v3.12.3
Kubernetes cluster: EKS 1.24

**Steps to reproduce**

`values.yaml` contents:
```
            Conditions:
              - Field: fake.field
                Operator: =
                Value: equal
              - Field: fake.field
                Operator: !=
                Value: not equal
              - Field: fake.field
                Operator: <=
                Value: less than or equal
              - Field: fake.field
                Operator: '>='
                Value: greater than or equal
              - Field: fake.field
                Operator: <
                Value: less than
              - Field: fake.field
                Operator: >
                Value: greater than
```

`helm upgrade --dry-run` output:
```          - Conditions:
            - Field: fake.field
              Operator: =
              Value: equal
            - Field: fake.field
              Operator: ""
              Value: not equal
            - Field: fake.field
              Operator: <=
              Value: less than or equal
            - Field: fake.field
              Operator: '>='
              Value: greater than or equal
            - Field: fake.field
              Operator: <
              Value: less than
            - Field: fake.field
              Operator: ""
              Value: greater than
```

**Additional context**
