### ISSUE TITLE
Configure separate affinities for refinery and refinery-redis deployments

### ISSUE THREAD

**Issue by alexgenco** [honeycombio/helm-charts#56]
I want to prevent `refinery` pods from being scheduled on the same node, but allow them to be scheduled on the same node as the `refinery-redis` pod. I have this right now:

```yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values: [refinery]
```

But this doesn't work because it applies to both the `refinery` and `refinery-redis` deployments, so the `refinery-redis` pod doesn't allow any `refinery` pods to be scheduled on its node. Is there a workaround here I'm missing, or would this require splitting out the affinities in the values file? I'm pretty new to k8s affinities.

Thanks!
