### ISSUE TITLE
Consider making apiKey an optional property in opentelemetry-collector

### ISSUE THREAD

**Issue by kthompson23** [honeycombio/helm-charts#9]
We place the configurations we override for all Helm charts we deploy into source control. Essentially we check in the name/version of the chart along with an overrides.yaml. Therefore we don't want to supply any secrets in values.yaml and instead use another process to deploy any needed secret resources.

Would you accept a PR to make `apiKey` an optional field? If the apiKey is not specified then the secret resource is not deployed and users of your chart would be required to deploy their own secret resource.

Something like:

```yaml
{{- if and (ne .Values.honeycomb.apiKey "YOUR_API_KEY") }}
apiVersion: v1
kind: Secret
metadata:
  name: honeycomb-{{ include "opentelemetry-collector.fullname" . }}
  labels:
  {{- include "opentelemetry-collector.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.honeycomb.apiKey | b64enc | quote }}
{{- end }}
```
