### ISSUE TITLE
Add ingressClassName support for ingress in secure-tenancy

### ISSUE THREAD

**Issue by yeukhon** [honeycombio/helm-charts#94]
**Is your feature request related to a problem? Please describe.**

Internally we have an ingress controller based on nginx. To use that feature we simply configure our values.yaml this way:

```
ingress:
--
  | enabled: true
  | ingressClassName: https-internal
  | hosts:
  | - host: foo.bar.com
  | paths: ["/"]
  | tls: []
```

However, the ingress did not work properly. My colleague pointed out that `ingressClassName` was missing in the manifest spec. This [feature](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#putting-it-all-together) was added a while back.

```
spec:
  rules:
    - host: foo.bar.com
      http:
        paths:
          - backend:
              service:
                name: secure-tenancy
                port:
                  name: http
            path: /
            pathType: Prefix
```

**Describe the solution you'd like**

The spec should have been this way:
```
spec:
  ingressClassName: https-internal
  rules:
...
```

**Describe alternatives you've considered**
N/A

**Additional context**
