### ISSUE TITLE
Consider Enabling `topologySpreadConstraints` for Refinery Helm Chart

### ISSUE THREAD

**Issue by bixu** [honeycombio/helm-charts#97]
**Is your feature request related to a problem? Please describe.**
I've seen behavior from the Refinery chart where pods will be scheduled on the same Kubernetes Node

**Describe the solution you'd like**
We've seen good success using `topologySpreadConstraints` to spread workload across K8s nodes using a `topologyKey` like `topology.kubernetes.io/zone`. Allowing operators to choose a `topologyKey` would allow us to mandate a more fault-tolerant HA topology.

**Comment by seh** [comment]
I patched this in via _kustomize_, per the following _Component_. For now, we're running only one Redis pod, but I wrote the same constraint for Redis to prepare for the future.

<details>
<summary>kustomize Component to add topology spread constraints</summary>

```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    group: apps
    kind: Deployment
    name: refinery
  patch: |-
    kind: Deployment
    metadata:
      name: .+
    spec:
      template:
        spec:
          topologySpreadConstraints:
          - topologyKey: kubernetes.io/hostname
            maxSkew: 1
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: refinery
                app.kubernetes.io/name: refinery
          - topologyKey: topology.kubernetes.io/zone
            maxSkew: 1
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: refinery
                app.kubernetes.io/name: refinery
- target:
    group: apps
    kind: Deployment
    name: refinery-redis
  patch: |-
    kind: Deployment
    metadata:
      name: .+
    spec:
      template:
        spec:
          topologySpreadConstraints:
          - topologyKey: kubernetes.io/hostname
            maxSkew: 1
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: refinery
                app.kubernetes.io/name: refinery-redis
          - topologyKey: topology.kubernetes.io/zone
            maxSkew: 1
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: refinery
                app.kubernetes.io/name: refinery-redis
```

</details>
